name: pytest-github-actions
run-name: running pytest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pwd
      - name: Run pytest
        env:
          PROJECT_HOME: /home/runner/work/pytest-github-actions/pytest-github-actions
          PYTHONPATH: /home/runner/work/pytest-github-actions/pytest-github-actions
        run: |
          pytest
